#!/bin/bash
if [[ $1 = -h ]] || [ ! $# -eq 1 ]
then
    echo "Usage: `basename $0` accountId"
   exit 
fi
curl -s -X GET "http://---host---:---port---/rest/accounts/$1" -H  "accept: application/json" | jq '.'
