#!/bin/bash
if [[ $1 = -h ]] || [ ! $# -eq 0 ]
then
    echo "Usage: `basename $0`"
   exit 
fi
curl -s -X GET "http://---host---:---port---/rest/accounts/hidden" -H  "accept: application/json" | jq '.'
