services:
  simpledtupay:
    build:
      context: ./simple-dtu-pay
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672 
    networks:
      - network

  bank:
    build:
      context: ../bank/bank_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - network

  account:
    build:
      context: ./account
      dockerfile: src/main/docker/Dockerfile.jvm
    ports: 
      - "8082:8082"
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
    networks:
      - network

  payment:
    build:
      context: ./payment
      dockerfile: src/main/docker/Dockerfile.jvm
    ports: 
      - "8083:8083"
    environment:
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
    networks:
      - network

  rabbit:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
    networks:
      - network

networks:
  network:
    driver: bridge