#!/bin/sh
set -e
rm -rf /tmp/banksrc
mkdir /tmp/banksrc
pushd src
for n in $(ls)
do
	 sed -e "s/---host---/$1/g" -e "s/---port---/$2/g" < $n > /tmp/banksrc/$n
	 chmod a+rx /tmp/banksrc/$n
done
popd
pushd /tmp/banksrc
zip ../tools.zip *
popd
mv /tmp/tools.zip ../bank_service/src/main/webapp

